
(venv) C:\Users\b3r1a\OneDrive\桌面\AdultOrNot>python .\scripts\specific_self_model_6-2.py
2024-07-18 20:58:32.978990: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-18 20:58:34.775882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1651 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Found 37681 validated image filenames belonging to 2 classes.
Found 16235 validated image filenames belonging to 2 classes.
2024-07-18 20:58:38.712790: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2024-07-18 20:58:40.565876: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2024-07-18 20:58:42.364460: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code -1, output:
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-07-18 20:58:44.518264: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37681/37681 [==============================] - 669s 18ms/step - loss: 0.7147 - accuracy: 0.5003 - val_loss: 0.6936 - val_accuracy: 0.5000

Epoch 00001: val_accuracy improved from -inf to 0.49997, saving model to best_specific_model.keras
Epoch 2/10
37681/37681 [==============================] - 662s 18ms/step - loss: 0.7037 - accuracy: 0.5019 - val_loss: 0.6937 - val_accuracy: 0.5000

Epoch 00002: val_accuracy did not improve from 0.49997
Epoch 3/10
19850/37681 [==============>...............] - ETA: 4:44 - loss: 0.6933 - accuracy: 0.4952Traceback (most recent call last):
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\scripts\specific_self_model_6-2.py", line 72, in <module>
    history = model.fit(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\engine\training.py", line 1189, in fit
    callbacks.on_train_batch_end(end_step, logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 435, in on_train_batch_end
    self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 295, in _call_batch_hook
    self._call_batch_end_hook(mode, batch, logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 315, in _call_batch_end_hook
    self._call_batch_hook_helper(hook_name, batch, logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 353, in _call_batch_hook_helper
    hook(batch, logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 1028, in on_train_batch_end
    self._batch_update_progbar(batch, logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\callbacks.py", line 1100, in _batch_update_progbar
    logs = tf_utils.sync_to_numpy_or_python_type(logs)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\utils\tf_utils.py", line 516, in sync_to_numpy_or_python_type
    return tf.nest.map_structure(_to_single_numpy_or_python_type, tensors)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\util\nest.py", line 869, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\util\nest.py", line 869, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\utils\tf_utils.py", line 512, in _to_single_numpy_or_python_type
    x = t.numpy()
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1094, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1060, in _numpy
    return self._numpy_internal()
KeyboardInterrupt
2024-07-18 21:26:07.886995: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
^C
(venv) C:\Users\b3r1a\OneDrive\桌面\AdultOrNot>python .\scripts\specific_self_model_6-2.py
2024-07-18 21:26:21.755184: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-18 21:26:22.949297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1651 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Found 37681 validated image filenames belonging to 2 classes.
Found 16235 validated image filenames belonging to 2 classes.
2024-07-18 21:26:25.208597: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2024-07-18 21:26:26.819376: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2024-07-18 21:26:27.961207: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code -1, output:
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-07-18 21:26:29.235222: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37681/37681 [==============================] - 663s 17ms/step - loss: 0.7089 - accuracy: 0.5021 - val_loss: 0.6933 - val_accuracy: 0.5000

Epoch 00001: val_accuracy improved from -inf to 0.49997, saving model to best_specific_model.keras
Epoch 2/10
37681/37681 [==============================] - 660s 18ms/step - loss: 0.6934 - accuracy: 0.5020 - val_loss: 0.6931 - val_accuracy: 0.5000

Epoch 00002: val_accuracy improved from 0.49997 to 0.50003, saving model to best_specific_model.keras
Epoch 3/10
19308/37681 [==============>...............] - ETA: 4:52 - loss: 0.6934 - accuracy: 0.4948Traceback (most recent call last):
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\scripts\specific_self_model_6-2.py", line 72, in <module>
    history = model.fit(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\engine\training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt
2024-07-18 21:53:38.144085: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
^C
(venv) C:\Users\b3r1a\OneDrive\桌面\AdultOrNot>python .\scripts\specific_self_model_6-2.py
2024-07-18 21:53:45.350047: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-18 21:53:45.948882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1651 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Found 37681 validated image filenames belonging to 2 classes.
Found 16235 validated image filenames belonging to 2 classes.
2024-07-18 21:53:48.060140: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2024-07-18 21:53:49.269491: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2024-07-18 21:53:50.155232: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code -1, output:
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-07-18 21:53:51.193847: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
29844/37681 [======================>.......] - ETA: 2:04 - loss: 0.7113 - accuracy: 0.5029Traceback (most recent call last):
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\scripts\specific_self_model_6-2.py", line 72, in <module>
    history = model.fit(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\keras\engine\training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\b3r1a\OneDrive\桌面\AdultOrNot\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt
2024-07-18 22:01:47.265250: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
^C
(venv) C:\Users\b3r1a\OneDrive\桌面\AdultOrNot>python .\scripts\specific_self_model_6-2.py
2024-07-18 22:01:55.608862: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-18 22:01:56.190236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1651 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Found 37681 validated image filenames belonging to 2 classes.
Found 16235 validated image filenames belonging to 2 classes.
2024-07-18 22:01:58.296988: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2024-07-18 22:01:59.514293: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2024-07-18 22:02:00.415639: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code -1, output:
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-07-18 22:02:01.386250: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37681/37681 [==============================] - 667s 18ms/step - loss: 0.6529 - accuracy: 0.6242 - val_loss: 0.5561 - val_accuracy: 0.7465

Epoch 00001: val_accuracy improved from -inf to 0.74654, saving model to best_specific_model.keras
Epoch 2/10
37681/37681 [==============================] - 667s 18ms/step - loss: 0.5363 - accuracy: 0.7509 - val_loss: 0.5590 - val_accuracy: 0.7476

Epoch 00002: val_accuracy improved from 0.74654 to 0.74764, saving model to best_specific_model.keras
Epoch 3/10
37681/37681 [==============================] - 666s 18ms/step - loss: 0.4964 - accuracy: 0.7742 - val_loss: 0.6578 - val_accuracy: 0.7167

Epoch 00003: val_accuracy did not improve from 0.74764

Epoch 00003: ReduceLROnPlateau reducing learning rate to 0.00020000000949949026.
Epoch 4/10
37681/37681 [==============================] - 663s 18ms/step - loss: 0.4214 - accuracy: 0.8128 - val_loss: 0.7765 - val_accuracy: 0.7132

Epoch 00004: val_accuracy did not improve from 0.74764
Epoch 5/10
37681/37681 [==============================] - 664s 18ms/step - loss: 0.3988 - accuracy: 0.8261 - val_loss: 0.7264 - val_accuracy: 0.7159

Epoch 00005: val_accuracy did not improve from 0.74764

Epoch 00005: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 6/10
37681/37681 [==============================] - 662s 18ms/step - loss: 0.3745 - accuracy: 0.8367 - val_loss: 0.5639 - val_accuracy: 0.7650

Epoch 00006: val_accuracy improved from 0.74764 to 0.76501, saving model to best_specific_model.keras
Epoch 7/10
37681/37681 [==============================] - 664s 18ms/step - loss: 0.3655 - accuracy: 0.8418 - val_loss: 0.5711 - val_accuracy: 0.7619

Epoch 00007: val_accuracy did not improve from 0.76501
Epoch 8/10
37681/37681 [==============================] - 664s 18ms/step - loss: 0.3577 - accuracy: 0.8459 - val_loss: 0.6505 - val_accuracy: 0.7336

Epoch 00008: val_accuracy did not improve from 0.76501
Epoch 9/10
37681/37681 [==============================] - 663s 18ms/step - loss: 0.3522 - accuracy: 0.8493 - val_loss: 0.6286 - val_accuracy: 0.7669

Epoch 00009: val_accuracy improved from 0.76501 to 0.76692, saving model to best_specific_model.keras
Epoch 10/10
37681/37681 [==============================] - 663s 18ms/step - loss: 0.3445 - accuracy: 0.8518 - val_loss: 0.5633 - val_accuracy: 0.7715

Epoch 00010: val_accuracy improved from 0.76692 to 0.77154, saving model to best_specific_model.keras

(venv) C:\Users\b3r1a\OneDrive\桌面\AdultOrNot>